language: r
r:
  - release
  - devel
  - oldrel
cache: packages
matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
    - os: linux
      dist: trusty
      sudo: false
    - os: osx
      osx_image: xcode8
      latex: false
    - os: osx
      osx_image: beta-xcode6.2
      disable_homebrew: true
      latex: false
notifications:
  email:
    - jdunham@mit.edu
r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'library(covr); codecov(line_exclusions = list("src/include/models.hpp"))'
