language: r
cache: packages
matrix:
  include:
    - os: linux
      dist: precise
      r:
        - release
        - devel
        - oldrel
    - os: linux
      dist: trusty
      r:
        - release
        - devel
        - oldrel
    - os: osx
      osx_image: xcode8
      latex: false
      r:
        - release
        - devel
        - oldrel
    - os: osx
      osx_image: beta-xcode6.2
      disable_homebrew: true
      latex: false
      r:
        - release
        - devel
        - oldrel
notifications:
  email:
    - jdunham@mit.edu
r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'library(covr); codecov(line_exclusions = list("src/include/models.hpp"))'
