# .travis.yml for R projects from https://github.com/craigcitro/r-travis
language: r
sudo: required
warnings_are_errors: true

env:
 global:
   - CRAN: https://cran.rstudio.com

notifications:
  email:
    - jdunham@mit.edu

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr); codecov(line_exclusions = list("src/include/models.hpp"))'
