# .travis.yml for R projects from https://github.com/craigcitro/r-travis
language: r
cache: packages

notifications:
  email:
    - jdunham@mit.edu

r_github_packages:
  - jimhester/covr
  - jamesdunham/dgodata

after_success:
  - Rscript -e 'library(covr); codecov(line_exclusions = list("src/include/models.hpp"))'
